In [120]:
import logging
import os

import numpy as np
import torch
import gpytorch
import matplotlib.pyplot as plt
import seaborn as sns
import pyro
import pyro.distributions as dist

import tqdm

In [53]:
mean = torch.randn(())
mean

tensor(0.5419)

In [54]:
mean.unsqueeze(-1)

tensor([0.5419])

In [66]:
mean.unsqueeze(-1).expand((5,))

tensor([0.5419, 0.5419, 0.5419, 0.5419, 0.5419])

In [67]:
mean.unsqueeze(-1).expand((5,2))

tensor([[0.5419, 0.5419],
        [0.5419, 0.5419],
        [0.5419, 0.5419],
        [0.5419, 0.5419],
        [0.5419, 0.5419]])

In [80]:
torch.empty((0,)).shape

torch.Size([0])

In [119]:
x=torch.empty(5,6,4,1)
y=torch.empty(  6,1,9)
(x+y).shape

torch.Size([5, 6, 4, 9])

In [123]:
torch.randn(2, pyro.distributions.constraints.positive)

TypeError: randn(): argument 'size' must be tuple of ints, but found element of type _GreaterThan at pos 2

In [125]:
torch.randn(2)

tensor([ 1.5002, -2.1440])

In [128]:
torch.tensor([[.2, .3], [.5, .2]])

tensor([[0.2000, 0.3000],
        [0.5000, 0.2000]])

In [153]:
norm = dist.MultivariateNormal(torch.randn(2), torch.tensor([[1., .3], [.3, 1.]]))

In [155]:
samples = norm.sample(torch.tensor([5]))

In [158]:
norm.log_prob(samples)

tensor([-2.5952, -2.3316, -2.2052, -2.7886, -3.5112])

In [162]:
norm.event_shape == (2,)

True

In [152]:
torch.tensor([0.1, 0.2, 0.3, 0.4]).expand([3, 4])

tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.1000, 0.2000, 0.3000, 0.4000],
        [0.1000, 0.2000, 0.3000, 0.4000]])

In [168]:
test = dist.Normal(torch.zeros(3,4,5), 1).

In [187]:
test.to_event(2).event_shape

torch.Size([4, 5])

In [191]:
test.to_event(1).sample((3,)).shape

torch.Size([3, 3, 4, 5])

In [151]:
dist.Normal(torch.zeros(3,4,5), 1).to_event(2)

tensor([[-0.5635,  1.0474],
        [-1.6609,  1.8796],
        [ 0.0715,  1.7856],
        [-1.0082,  0.7676],
        [-1.7652,  0.1882]])

In [103]:
x=torch.empty(5,2,4,1)
y=torch.empty(  5,1,1)
(x+y)

RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1